// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first, then .env
dotenv.config({ path: ".env.local" });
dotenv.config();

// Use a placeholder during Docker build when DATABASE_URL is not available
// This is only used for prisma generate, not for runtime
const databaseUrl = process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
